### ISSUE TITLE
unable to install the project dependencies because of weasyprint

### ISSUE THREAD

**Issue by salmanishere** [Jooyeshgar/amir#16]
Hey, I wanted to install this software but _weasyprint_ says that it doesn't support python2 anymore.

```
        'WeasyPrint does not support Python 2.x anymore. '
    RuntimeError: WeasyPrint does not support Python 2.x anymore. Please use Python 3 or install an older version of WeasyPrint.
```

**Comment by niloofarfs** [comment]
Hi. Could you please tell us what is your OS?

**Comment by salmanishere** [comment]
Debian9 (Stretch) x86_64

**Comment by niloofarfs** [comment]
@salmanishere  Could you change `requirements.txt` file and change weasyprint version like this:

`weasyprint == 0.42.3`

Please let us know if the problem is solved or not.

**Comment by salmanishere** [comment]
I could bypass this error by specifying this specific version.

**Comment by ebraminio** [comment]
No more an issue now that we are actually migrated to python3 (the reason I went for the migration at the first hand)

Thanks!
