### ISSUE TITLE
ImportError: No module named glade

### ISSUE THREAD

**Issue by HassanHeydariNasab** [Jooyeshgar/amir#2]
I've installed dependencies from https://github.com/Jooyeshgar/amir/blob/master/debian/control
When I run amir in terminal, I see this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/amir", line 57, in <module>
    import gtk,gtk.glade
ImportError: No module named glade
```
OS: Ubuntu 17.10

**Comment by hadi60** [comment]
Please install python-glade2 and check again
If this solves your issue please let us know.

**Comment by HassanHeydariNasab** [comment]
solved!
