### ISSUE TITLE
حذف سازگاری با پایتون ۲

### ISSUE THREAD

**Issue by ebraminio** [Jooyeshgar/amir#23]
تو تغییرات اخیر پشتیبانی از پایتون ۳ در برنامه اضافه شده که به نظر پایدار هم هست. آیا پشتیبانی از پایتون ۲ همچنان نیاز هست؟ اگه نیازی نیست با حذف سازگاری با پایتون ۲ یه سری از کدها ساده‌تر می‌شن

**Comment by hadi60** [comment]
پشتیبانی از پایتون ۲ نیاز نیست ولی به نظرم عجله ای هم نیست 
تقریبا کد نویسی نداریم که ساده تر باشه
اگر ساخته پکیج ها رو ساده تر می کنه انجامش بدیم ولی اگر نمی کنه باشه بهتره

**Comment by ebraminio** [comment]
#40
