### ISSUE TITLE
ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by MehrdadLinux** [Jooyeshgar/amir#35]
سلام من دستور العمل نصب را پیگیری کردم 
با ارور زیر مواحه شدم
Traceback (most recent call last):
  File "./amir", line 46, in <module>
    from amir import automaticaccounting, bankaccountsui
  File "/home/....../lib/python3.6/site-packages/amir-0.3.0-py3.6.egg/amir/automaticaccounting.py", line 2, in <module>
    from gi.repository import Gtk
ModuleNotFoundError: No module named 'gi'

از دستور زیر برای حل مشکلات استفاده شده ولی مشکل همچنان سر جای خودش است 
apt-get install python3-gi

ورژن ها
Python 3.6.8 :: Anaconda, In

از ویرچوال env
استفاده کردم جواب فعلا نگرفتم نمدونم مشکل چیه 

من ایشیو تمپلیت امیر را هم پیدا نکردم اگر ان را هم بسازید عالی میشه

**Comment by hadi60** [comment]
روی مینت نصب python3-gi مشکل رو برای من حل کرد
ولی ظاهرا مشکلات زیاد دیگه ای داریم که نمی دونم چرا قبلا ندیده بودم 
شما یه پول بکن و دایرکتوری .amir روی توی هوم کاربر پاک کن
ببین هنوز هم مشکل هست

**Comment by ebraminio** [comment]
> ولی ظاهرا مشکلات زیاد دیگه ای داریم که نمی دونم چرا قبلا ندیده بودم

من هم نمی‌دونم اواخر که با این پروژه کار می‌کردم باید می‌دیدم این مشکلارو!

**Comment by hadi60** [comment]
من همه رو تست کردم بعد مرج ها رو اکسپت کردم
احتمال می دم اشتباها از کدهای قدیم داشته می خونده که نصب بوده رو سیستم
راستش تعجب هم کردم که چرا هیچ ایرادی نداره
الان مشکلات زیر ساختی هستند مثلا متغیری که رفرنس بوده به متغیر اصلی الان
کپی مقدار اون رو داره که خوب اصلا کار نمی کنه و توی تقریبا تمام فایل ها هم
هست
config
رو می گم

**Comment by MehrdadLinux** [comment]
این مشکل با اناکوندا است اگر اناکوندا را حدف کنید مشکل حل میشود 
مشکلش با اناکوندا چیه نمیدومم به هر حال بعد از حذف اناکوندا 
pip 
خراب میشود که باید درست شود 
مشکل با حذف اناکوندا حل شد
